var nameList = [
  "Time",
  "Past",
  "Future",
  "Dev",
  "Fly",
  "Flying",
  "Soar",
  "Soaring",
  "Power",
  "Falling",
  "Fall",
  "Jump",
  "Cliff",
  "Mountain",
  "Rend",
  "Red",
  "Blue",
  "Green",
  "Yellow",
  "Gold",
  "Demon",
  "Demonic",
  "Panda",
  "Cat",
  "Kitty",
  "Kitten",
  "Zero",
  "Memory",
  "Trooper",
  "XX",
  "Bandit",
  "Fear",
  "Light",
  "Glow",
  "Tread",
  "Deep",
  "Deeper",
  "Deepest",
  "Mine",
  "Your",
  "Worst",
  "Enemy",
  "Hostile",
  "Force",
  "Video",
  "Game",
  "Donkey",
  "Mule",
  "Colt",
  "Cult",
  "Cultist",
  "Magnum",
  "Gun",
  "Assault",
  "Recon",
  "Trap",
  "Trapper",
  "Redeem",
  "Code",
  "Script",
  "Writer",
  "Near",
  "Close",
  "Open",
  "Cube",
  "Circle",
  "Geo",
  "Genome",
  "Germ",
  "Spaz",
  "Shot",
  "Echo",
  "Beta",
  "Alpha",
  "Gamma",
  "Omega",
  "Seal",
  "Squid",
  "Money",
  "Cash",
  "Lord",
  "King",
  "Duke",
  "Rest",
  "Fire",
  "Flame",
  "Morrow",
  "Break",
  "Breaker",
  "Numb",
  "Ice",
  "Cold",
  "Rotten",
  "Sick",
  "Sickly",
  "Janitor",
  "Camel",
  "Rooster",
  "Sand",
  "Desert",
  "Dessert",
  "Hurdle",
  "Racer",
  "Eraser",
  "Erase",
  "Big",
  "Small",
  "Short",
  "Tall",
  "Sith",
  "Bounty",
  "Hunter",
  "Cracked",
  "Broken",
  "Sad",
  "Happy",
  "Joy",
  "Joyful",
  "Crimson",
  "Destiny",
  "Deceit",
  "Lies",
  "Lie",
  "Honest",
  "Destined",
  "Bloxxer",
  "Hawk",
  "Eagle",
  "Hawker",
  "Walker",
  "Zombie",
  "Sarge",
  "Capt",
  "Captain",
  "Punch",
  "One",
  "Two",
  "Uno",
  "Slice",
  "Slash",
  "Melt",
  "Melted",
  "Melting",
  "Fell",
  "Wolf",
  "Hound",
  "Legacy",
  "Sharp",
  "Dead",
  "Mew",
  "Chuckle",
  "Bubba",
  "Bubble",
  "Sandwich",
  "Smasher",
  "Extreme",
  "Multi",
  "Universe",
  "Ultimate",
  "Death",
  "Ready",
  "Monkey",
  "Elevator",
  "Wrench",
  "Grease",
  "Head",
  "Theme",
  "Grand",
  "Cool",
  "Kid",
  "Boy",
  "Girl",
  "Vortex",
  "Paradox",
];

export default function randomNameGenerator() {
  return nameList[Math.floor(Math.random() * nameList.length)];
}

const meaningfulMessages = [
  "Believe in yourself, and you can achieve anything.",
  "Kindness is a language that the deaf can hear and the blind can see. -Mark Twain",
  "The journey of a thousand miles begins with one step. - Lao Tzu",
  "In the middle of every difficulty lies opportunity. -Albert Einstein",
  "Your time is limited, don't waste it living someone else's life.-Steve Jobs",
  "You are never too old to set another goal or to dream a new dream.-C.S. Lewis",
  "The only way to do great work is to love what you do.-Steve Jobs",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.-Winston Churchill",
  "The best way to predict the future is to create it.-Peter Drucker",
  "You are the author of your life story; make it a bestseller.",
  "Happiness is not something ready-made. It comes from your own actions.-Dalai Lama",
  "Don't count the days, make the days count.-Muhammad Ali",
  "The only thing we have to fear is fear itself.-Franklin D. Roosevelt",
  "You have the power to change your life. Don't be a passenger; be the driver.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.-Nelson Mandela",
  "Embrace the glorious mess that you are.",
  "Life is what happens when you're busy making other plans.-John Lennon",
  "The only limit to our realization of tomorrow will be our doubts of today.-Franklin D. Roosevelt",
  "Success is walking from failure to failure with no loss of enthusiasm.-Winston Churchill",
  "The purpose of our lives is to be happy.-Dalai Lama",
  "You are never too important to be kind to others.",
  "You miss 100% of the shots you don't take.-Wayne Gretzky",
  "The only person you should try to be better than is the person you were yesterday.",
  "Dream big and dare to fail.-Norman Vaughan",
  "Happiness is not the absence of problems; it's the ability to deal with them.",
  "Life is short, and it's up to you to make it sweet.",
  "In the end, we will remember not the words of our enemies, but the silence of our friends.-Martin Luther King Jr.",
  "Don't watch the clock; do what it does. Keep going.-Sam Levenson",
  "You are stronger than you think. Believe in yourself and push your limits.",
  "Your time is now. Start where you are. Use what you have. Do what you can.-Arthur Ashe",
];

export function randomMessageGenerator() {
    return meaningfulMessages[Math.floor(Math.random() * meaningfulMessages.length)];
  }
  
